### ISSUE TITLE
index.html以外のページでのcssを改善

### ISSUE THREAD

**Issue by physics11688** [TakajoDormitory/HomePage#30]
## リクエスト内容
index.html以外のページでのcssを改善
とくに左寄せで文章化記述されているのはこれから変更される？
.container 記述の必要あり

## リクエストした理由
おそらくまだ手を付けてないだけだと思うけど、一応ToDoとして上げておきます。

**Comment by c19yamamoto** [comment]
全ページに反映させているCSS([common.css](https://github.com/TakajoDormitory/HomePage/blob/main/style/common.css))をアップデートしました。
コンテンツ未制作のページを除いて、CSSが改善されました。
