### ISSUE TITLE
tableの変更

### ISSUE THREAD

**Issue by physics11688** [TakajoDormitory/HomePage#31]
## リクエスト内容
cost.html における `table` はデザインを変更したほうがいいのでは？

## リクエストした理由
事務的すぎる様に見えるから
[coolなtable?](https://www.google.co.jp/search?q=css+table+cool&tbm=isch&ved=2ahUKEwiRlYW5oaXyAhXczIsBHYE5AfsQ2-cCegQIABAA&oq=css+table+cool&gs_lcp=CgNpbWcQAzIGCAAQCBAeOgUIABCABDoECAAQHjoECAAQEzoICAAQCBAeEBNQ-AdYjhFg1RJoAHAAeACAAW2IAc8DkgEDNC4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=udARYdHUGdyZr7wPgfOE2A8&bih=852&biw=1745)

**Comment by c19yamamoto** [comment]
デザインを変更しました。
